version: "3.9"
services:
  eurekaserver:
    build: ./eurekaserver/
    ports:
      - "8761:8761"
    image: "eurekaserver"
 
  zuul:
    build: ./Zuul-Gateway/
    ports:
      - "8763:8763"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eurekaserver:8761/eureka/
      zuul.routes.item-service.url: http://item-service:8088
      zuul.routes.category-service.url: http://category-service:8089
      zuul.routes.user-service.url: http://user-service:3000
    image: "zuul" 

  item-service:
    build: ./MS_stock/
    ports:
      - "8088:8088"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eurekaserver:8761/eureka/
    image: "item-service"

  category-service:
    build: ./MS_category/
    ports:
      - "8089:8089"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eurekaserver:8761/eureka/
    image: "category-service"    

  user-service:
    build: ./MS_user/
    ports:
      - "3000:3000"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eurekaserver:8761/eureka/
    image: "user-service"